import type { Font } from "./types";

/** Map MIME type to @font-face format() string */
export function formatFromMime(mime: string): string {
  switch (mime) {
    case "font/ttf": return "truetype";
    case "font/otf": return "opentype";
    case "font/woff": return "woff";
    case "font/woff2": return "woff2";
    default: return "truetype";
  }
}

/** Infer CSS font-weight and font-style from a font's name aliases */
export function inferWeightAndStyle(aliases: string[]): { weight: string; style: string } {
  const fullName = aliases.reduce((a, b) => (b.length > a.length ? b : a), "");
  const lower = fullName.toLowerCase();

  let weight = "normal";
  if (/ultra\s?light|hairline|thin/.test(lower)) weight = "100";
  else if (/extra\s?light/.test(lower)) weight = "200";
  else if (/\blight\b/.test(lower)) weight = "300";
  else if (/\bheavy\b|\bblack\b/.test(lower)) weight = "900";
  else if (/extra\s?bold|ultra\s?bold/.test(lower)) weight = "800";
  else if (/semi\s?bold|demi\s?bold/.test(lower)) weight = "600";
  else if (/\bbold\b/.test(lower)) weight = "700";
  else if (/\bmedium\b/.test(lower)) weight = "500";

  let style = "normal";
  if (/\bitalic\b/.test(lower)) style = "italic";
  else if (/\boblique\b/.test(lower)) style = "oblique";

  return { weight, style };
}

const GENERIC_FONTS = new Set([
  "serif", "sans-serif", "monospace", "cursive", "fantasy",
  "system-ui", "ui-serif", "ui-sans-serif", "ui-monospace", "ui-rounded",
  "emoji", "math", "fangsong",
]);

export function isGenericFont(name: string): boolean {
  return GENERIC_FONTS.has(name.toLowerCase());
}

const SYSTEM_FONTS = new Set([
  "times new roman", "arial", "helvetica", "courier new", "courier",
  "georgia", "palatino", "garamond", "bookman", "tahoma", "verdana",
  "impact", "comic sans ms", "trebuchet ms", "lucida console", "lucida sans",
  "calibri", "cambria", "consolas", "segoe ui", "symbol", "wingdings",
  "webdings", "ms gothic", "ms mincho", "arial black", "arial narrow",
  "book antiqua", "century gothic", "franklin gothic medium",
]);

export function isSystemFont(name: string): boolean {
  return SYSTEM_FONTS.has(name.toLowerCase());
}

/** Find the best matching font from our library for a given font name */
export function findBestFontMatch(targetName: string, fontList: Font[]): Font | null {
  const targetLower = targetName.toLowerCase();
  const targetNorm = targetLower.replace(/[^a-z0-9]/g, "");

  // Pass 1: exact alias match (case-insensitive)
  for (const font of fontList) {
    const allNames = [font.family, ...(font.font_aliases || [])];
    for (const name of allNames) {
      if (name.toLowerCase() === targetLower) return font;
    }
  }

  // Pass 2: normalized match (strip spaces, hyphens, etc.)
  for (const font of fontList) {
    const allNames = [font.family, ...(font.font_aliases || [])];
    for (const name of allNames) {
      if (name.toLowerCase().replace(/[^a-z0-9]/g, "") === targetNorm) return font;
    }
  }

  // Pass 3: family prefix match
  let bestMatch: Font | null = null;
  let bestLen = 0;
  for (const font of fontList) {
    const familyLower = font.family.toLowerCase();
    if (targetLower.startsWith(familyLower) || familyLower.startsWith(targetLower)) {
      if (familyLower.length > bestLen) {
        bestMatch = font;
        bestLen = familyLower.length;
      }
    }
  }
  return bestMatch;
}

/**
 * After docx-preview renders, scan the entire rendered DOM for font-family
 * references. For any font name that doesn't match a loaded FontFace, search
 * our font library for the best match and register a bridge FontFace.
 */
export function bridgeDocxFonts(
  container: HTMLElement,
  fontList: Font[],
  blobUrls: Map<string, string>,
  alreadyRegistered: Set<string>,
): FontFace[] {
  const registered = new Set(alreadyRegistered);
  const bridgedFaces: FontFace[] = [];
  const bridgedRules: string[] = [];

  // 1. Collect every font name referenced in the rendered HTML
  const referencedFonts = new Set<string>();

  // From inline styles on elements
  const styledEls = container.querySelectorAll<HTMLElement>("[style]");
  for (const el of styledEls) {
    const ff = el.style.fontFamily;
    if (ff) {
      for (const part of ff.split(",")) {
        const name = part.trim().replace(/["']/g, "");
        if (name && !isGenericFont(name) && !name.startsWith("var(") && !name.startsWith("__")) {
          referencedFonts.add(name);
        }
      }
    }
  }

  // From CSS stylesheets generated by docx-preview
  const styleEls = container.querySelectorAll("style");
  for (const style of styleEls) {
    const text = style.textContent || "";
    const matches = text.matchAll(/font-family:\s*([^;}\n]+)/g);
    for (const m of matches) {
      for (const part of m[1].split(",")) {
        const name = part.trim().replace(/["']/g, "").replace(/var\([^)]+\)/g, "").trim();
        if (name && !isGenericFont(name) && !name.startsWith("var(") && !name.startsWith("__")) {
          referencedFonts.add(name);
        }
      }
    }
    const varMatches = text.matchAll(/--(docx-\w+-font)\s*:\s*"?([^";}\n]+)"?/g);
    for (const vm of varMatches) {
      const fontName = vm[2].trim().replace(/["']/g, "");
      if (fontName && !isGenericFont(fontName)) {
        referencedFonts.add(fontName);
      }
    }
  }

  // 2. For each referenced font that isn't already loaded, find a match and bridge
  for (const fontName of referencedFonts) {
    if (registered.has(fontName.toLowerCase())) continue;
    if (isSystemFont(fontName)) continue;

    const match = findBestFontMatch(fontName, fontList);
    if (!match) continue;

    const url = blobUrls.get(match.id);
    if (!url) continue;

    const fmt = formatFromMime(match.mime_type);
    const aliases = match.font_aliases?.length ? match.font_aliases : [match.family];
    const { weight, style } = inferWeightAndStyle(aliases);

    try {
      const face = new FontFace(fontName, `url("${url}") format("${fmt}")`, { weight, style });
      face.load().then(() => document.fonts.add(face));
      bridgedFaces.push(face);
      registered.add(fontName.toLowerCase());

      bridgedRules.push(`@font-face {
  font-family: "${fontName}";
  src: url("${url}") format("${fmt}");
  font-weight: ${weight};
  font-style: ${style};
  font-display: swap;
}`);
    } catch {
      console.warn(`Failed to bridge font "${fontName}"`);
    }
  }

  // 3. Inject bridged @font-face rules into the container
  if (bridgedRules.length > 0) {
    const bridgeStyle = document.createElement("style");
    bridgeStyle.textContent = bridgedRules.join("\n");
    container.prepend(bridgeStyle);
  }

  // 4. Fix theme font CSS variables
  for (const style of styleEls) {
    const text = style.textContent || "";
    const varDefs = text.matchAll(/--(docx-\w+-font)\s*:\s*"?([^";}\n]+)"?/g);
    for (const m of varDefs) {
      const varName = m[1];
      const fontName = m[2].trim().replace(/["']/g, "");
      if (fontName && registered.has(fontName.toLowerCase())) {
        container.style.setProperty(`--${varName}`, `"${fontName}"`);
      }
    }
  }

  // 5. Fix the wrapper default font if it's Times New Roman
  const wrapper = container.querySelector<HTMLElement>('[class*="docx-preview-wrapper"]');
  if (wrapper) {
    const currentFont = wrapper.style.fontFamily?.replace(/["']/g, "").trim();
    if (currentFont === "Times New Roman" || !currentFont) {
      const fontCounts = new Map<string, number>();
      const spans = wrapper.querySelectorAll<HTMLElement>("span[style]");
      for (const span of spans) {
        const match = (span.getAttribute("style") || "").match(/font-family:\s*([^;]+)/);
        if (!match) continue;
        const primary = match[1].split(",")[0].trim().replace(/["']/g, "");
        if (!primary || isGenericFont(primary) || primary === "Times New Roman" || primary.startsWith("__")) continue;
        fontCounts.set(primary, (fontCounts.get(primary) || 0) + 1);
      }
      let bestFont = "";
      let bestCount = 0;
      for (const [font, count] of fontCounts) {
        if (count > bestCount) { bestFont = font; bestCount = count; }
      }
      if (bestFont) {
        wrapper.style.fontFamily = `"${bestFont}", "${currentFont || "Times New Roman"}"`;
      }
    }
  }

  return bridgedFaces;
}
